[package]
name = "pacman-rs"
version = "0.1.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[dependencies]
gl = { path = "gl" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "shellscalingapi", "errhandlingapi"] }

[workspace]