[package]
name = "pacman"
version = "0.1.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
gl = { path = "gl" }
platform = { path = "platform" }
lazy_static = "1.0"

[workspace]