[package]
name = "pacman"
version = "0.1.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
log = "0.4"
time = "0.1"
lazy_static = "1.0"

gl = { path = "gl" }
platform = { path = "platform" }

[workspace]