[package]
name = "profiler-macro"
version = "0.1.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"

[dependencies.syn]
version = "0.15"
features = ["full"]
